#version 460 core

layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D screen;
layout(rgba32f, binding = 1) uniform image3D voxel_grid;

ivec3 voxel_grid_size = imageSize(voxel_grid);

uniform vec3 camera_position;
uniform vec3 camera_direction;
uniform vec3 camera_up;
uniform vec3 camera_right;

bool aabb_intersect(vec3 ray_origin, vec3 ray_direction, vec3 box_min, vec3 box_max, out vec3 hit_point)
{
    vec3 entry_point = ray_origin;

    vec3 t1 = (box_min - ray_origin) / ray_direction;
    vec3 t2 = (box_max - ray_origin) / ray_direction;

    vec3 t_min = min(t1, t2);
    vec3 t_max = max(t1, t2);

    float t_entry = max(max(t_min.x, t_min.y), t_min.z);
    float t_exit = min(min(t_max.x, t_max.y), t_max.z);

    if (t_entry > t_exit || t_exit < 0.0) {
        return false;
    }

    if (t_entry > 0.0) {
        entry_point = ray_origin + ray_direction * t_entry;
    }

    hit_point = entry_point;
    return true;
}

vec4 cast_ray(vec3 ray_origin, vec3 ray_direction, out vec3 hit_point) {

    vec3 entry_point;

    if (!aabb_intersect(ray_origin, ray_direction, vec3(0), voxel_grid_size, entry_point))
    {
        return vec4(0.0);
    }
    
    ivec3 pos = ivec3(floor(entry_point)); 
    const ivec3 step = ivec3(sign(ray_direction));
    
    const vec3 tDelta = abs(1.0 / ray_direction);  
    vec3 tMax = vec3(
        (step.x > 0 ? (float(pos.x) + 1.0 - entry_point.x) : (entry_point.x - float(pos.x))) * tDelta.x,
        (step.y > 0 ? (float(pos.y) + 1.0 - entry_point.y) : (entry_point.y - float(pos.y))) * tDelta.y,
        (step.z > 0 ? (float(pos.z) + 1.0 - entry_point.z) : (entry_point.z - float(pos.z))) * tDelta.z
    );

    vec4 color = vec4(0.0);

    do {
        vec4 voxel_color = vec4(imageLoad(voxel_grid, pos));

        if (voxel_color.a > 0.0) {
            color.rgb = mix(color.rgb, voxel_color.rgb, voxel_color.a * (1.0 - color.a));
            color.a += voxel_color.a * (1.0 - color.a);
        }

        if (color.a >= 1.0) {
            break;
        }

        if (tMax.x < tMax.y) {
            if (tMax.x < tMax.z) {
                pos.x += step.x;
                tMax.x += tDelta.x;
            } else {
                pos.z += step.z;
                tMax.z += tDelta.z;
            }
        } else {
            if (tMax.y < tMax.z) {
                pos.y += step.y;
                tMax.y += tDelta.y;
            } else {
                pos.z += step.z;
                tMax.z += tDelta.z;
            }
        }
    } while (all(greaterThanEqual(pos, ivec3(0))) && all(lessThan(pos, voxel_grid_size)));

    hit_point = pos;
    aabb_intersect(ray_origin, ray_direction, pos, pos + vec3(1), hit_point);

    return color;
}


void main()
{
    ivec2 pixel_coordinates = ivec2(gl_GlobalInvocationID.xy);
    ivec2 screen_size = imageSize(screen);
    
    vec2 coordinates = (2.0 * vec2(pixel_coordinates) / vec2(screen_size) - 1.0);
    
    float aspect_ratio = float(screen_size.x) / float(screen_size.y);
    float fov = 60.0;
    float tan_half_fov = tan(radians(fov) / 2.0);
    vec3 ray_origin = camera_position;
    vec3 ray_direction = normalize(
        (-coordinates.x * camera_right * aspect_ratio * tan_half_fov +
        coordinates.y * camera_up * tan_half_fov +
        camera_direction)
    );


    vec3 hit_point;
    vec4 base_color = cast_ray(ray_origin, ray_direction, hit_point);
    vec3 light_position = vec3(voxel_grid_size.xy * 2, 0); // changing this to camera_position makes it crash
    vec3 light_direction = normalize(light_position - hit_point);
    vec4 light_color = cast_ray(hit_point + light_direction, light_direction, hit_point);

    imageStore(screen, pixel_coordinates, base_color - 0.4 * light_color);
}